substitutions:
  device_id: "02"  # Change to "01" or "02" to switch devices

esphome:
  name: rfid${device_id}
  includes:
    - src/RFID_command.h
    - M5RFID.h
    - src/RFID_command.cpp
    - src/RFID_command_basics.cpp
    - src/my_helpers.h
    - src/my_helpers.cpp

#globals:
#  - id: old_red
#    type: float
#    initial_value: '0.0'
#  - id: old_green
#    type: float
#    initial_value: '0.0'
#  - id: old_blue
#    type: float
#    initial_value: '0.0'
#  - id: old_brightness
#    type: float
#    initial_value: '0.0'



esp32:
  board: m5stack-core-esp32
  framework:
    type: arduino

wifi:
  <<: !include ./wifi.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "BrutaalTracking Fallback Hotspot"
    password: "0yyQtzyIpw3z"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  encryption:
#    key: "ZrlVfKcHDpx7uRtPyGfvwao8D8aSyOgJVCvYvDQ6CKI="
mqtt:
  #broker: 10.17.0.2
  broker: 10.80.0.1
  topic_prefix: r
  client_id: rfid${device_id}
  on_connect:
    then:
      - light.turn_on:
          id: fastled_light
          red: 0%
          green: 100%
          blue: 0%
          brightness: 50%
          transition_length: 0.5s
  on_disconnect:
    then:
      - light.turn_on:
          id: fastled_light
          red: 100%
          green: 0%
          blue: 0%
          brightness: 50%
          transition_length: 0.5s

ota:
  - platform: esphome
    password: "srTcdPLRnv5wDnf"
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Sofia
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org

light:
  - platform: fastled_clockless
    chipset: SK6812
    pin: 27
    num_leds: 1
    rgb_order: GRB
    name: "FastLED Light"
    id: fastled_light
    restore_mode: ALWAYS_OFF
    effects:
      - random:
          name: Random Effect With Custom Values
          transition_length: 5s
          update_interval: 7s
binary_sensor:
  - platform: gpio
    pin: 39
    name: "Button"
    on_release:
      - script.execute: melody

        #binary_sensor:
        #  - platform: gpio
        #    pin:
        #      number: 39
        #      inverted: true
        #    id: wiggle_button
        #    name: "Wiggle Button"
        #    on_release:
        #    - switch.toggle: wiggler

external_components:
  - source:
      type: local
      path: esphome/components
    components: [m5rfid]

text_sensor:
  - platform: m5rfid
    name: "${device_id}"
    id: m5rfid_sensor
    on_value:
      then:
        - script.execute: flash_led_white
        - script.execute: melody

button:
  - platform: output
    name: "Buzzer"
    # Example usage in an automation
    duration: "5000ms"
    output: buzzer
    on_press:
      - script.execute: melody


output:
  - platform: ledc
    ######################################################
    # One buzzer leg connected to GPIO12, the other to GND
    ######################################################
    pin: GPIO25
    id: buzzer

script:
  - id: flash_led_white
    then:
      # Store current LED color
      #- lambda: |-
      #    auto light = id(fastled_light);
      #    id(old_red) = light->remote_values.get_red();
      #    id(old_green) = light->remote_values.get_green();
      #    id(old_blue) = light->remote_values.get_blue();
      #    id(old_brightness) = light->remote_values.get_brightness();
      
      - repeat:
          count: 1
          then:
            - light.turn_on:
                id: fastled_light
                red: 100%
                green: 100%
                blue: 100%
                brightness: 100%
                transition_length: 0s
            - delay: 50ms
            - light.turn_off:
                id: fastled_light
                transition_length: 0s
      # Restore original color
      #- lambda: |-
      #    auto light = id(fastled_light);
      #    light->make_call().set_red(id(old_red)).set_green(id(old_green)).set_blue(id(old_blue)).set_brightness(id(old_brightness)).perform();

  - id: melody
    then:
      # Extended melody with multiple notes
      - output.turn_on: buzzer
      - output.ledc.set_frequency:
          id: buzzer
          frequency: "4000Hz"
      - output.set_level:
          id: buzzer
          level: "50%"
      - delay: "50ms"
      - output.turn_off: buzzer
