esphome:
  name: rfid01
  includes:
    - src/RFID_command.h
    - M5RFID.h
    - src/RFID_command.cpp
    - src/RFID_command_basics.cpp
    - src/my_helpers.h
    - src/my_helpers.cpp

esp32:
  board: m5stack-core-esp32

wifi:
  <<: !include ./wifi.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "M5Atomlite2 Fallback Hotspot"
    password: "0yyQtzyIpw3z"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  encryption:
#    key: "ZrlVfKcHDpx7uRtPyGfvwao8D8aSyOgJVCvYvDQ6CKI="
mqtt:
  broker: 10.17.0.2
  topic_prefix: rfid/01/

ota:
  - platform: esphome
    password: "srTcdPLRnv5wDnf"

light:
  - platform: fastled_clockless
    chipset: SK6812
    pin: 27
    num_leds: 1
    rgb_order: GRB
    name: "FastLED Light"
    effects:
      - random:
          name: Random Effect With Custom Values
          transition_length: 5s
          update_interval: 7s
binary_sensor:
  - platform: gpio
    pin: 39
    name: "Button"
    on_release:
      - script.execute: melody

        #binary_sensor:
        #  - platform: gpio
        #    pin:
        #      number: 39
        #      inverted: true
        #    id: wiggle_button
        #    name: "Wiggle Button"
        #    on_release:
        #    - switch.toggle: wiggler

external_components:
  - source:
      type: local
      path: esphome/components
    components: [m5rfid]

text_sensor:
  - platform: m5rfid
    name: "M5RFID"
    id: m5rfid_sensor
    on_value:
      then:
        - script.execute: melody

button:
  - platform: output
    name: "Buzzer"
    # Example usage in an automation
    duration: "5000ms"
    output: buzzer
    on_press:
      - script.execute: melody


output:
  - platform: ledc
    ######################################################
    # One buzzer leg connected to GPIO12, the other to GND
    ######################################################
    pin: GPIO25
    id: buzzer

script:
  - id: melody
    then:
      - repeat:
          count: 1
          then:
           - repeat:
               count: 1
               then:
                 ######################################################
                 # Must be turned on before setting frequency & level
                 ######################################################
                 - output.turn_on: buzzer
                 ######################################################
                 # Frequency sets the wave size
                 ######################################################
                 - output.ledc.set_frequency:
                     id: buzzer
                     frequency: "4000Hz"
                 ######################################################
                 # level sets the %age time the PWM is on
                 ######################################################
                 - output.set_level:
                     id: buzzer
                     level: "50%"
                 - delay: "70ms"
                 - output.set_level:
                     id: buzzer
                     level: "0%"
